---
# ===========================================================
#  MTProxy — количество реплик и образ
# ===========================================================
mtproxy_replicas: 2
mtproxy_secret: "b3b34e89c9471207ad107a03b565e9a3"
mtproxy_image: "telegrammessenger/proxy:latest"
mtproxy_base_port: 4431
mtproxy_nat_internal_ip: "10.8.0.2"
mtproxy_nat_external_ip: "5.10.213.161"

# ===========================================================
#  HAProxy — балансировка и статистика
# ===========================================================
haproxy_image: "haproxy:2.9-alpine"
haproxy_frontend_port: 8443
haproxy_stats_port: 8404
haproxy_stats_user: admin
haproxy_stats_password: "Ch4ng3M3!"
haproxy_balance: leastconn
haproxy_tproxy: true
mtproxy_backend_ip: "10.8.0.2"

# ===========================================================
#  Путь к конфигу HAProxy на хосте
# ===========================================================
haproxy_config_dir: /etc/haproxy
haproxy_config_path: "{{ haproxy_config_dir }}/haproxy.cfg"

# ===========================================================
#  WireGuard
# ===========================================================
wireguard_listen_port: 51820
